name: newsfeedapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1  
  http: ^1.2.2
  provider: ^6.1.2
  url_launcher: ^6.3.0
  firebase_remote_config: ^5.1.2
  firebase_analytics: ^11.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700